# Generated by Django 4.2.1 on 2023-05-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment_writer_post_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
    ]
